### ISSUE TITLE
NODE_MODULE_VERSION?

### ISSUE THREAD

**Issue by vascott1** [jfarmer08/homebridge-wyze-smart-home#112]
**Describe Your Problem:**
After upgrading from 0.5.24 to 0.5.28 I am getting an error:

[04/07/2023, 10:43:53] Error: The module '/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
**Logs:**

```
[04/07/2023, 10:43:53] ====================
[04/07/2023, 10:43:53] ERROR LOADING PLUGIN homebridge-zigbee-nt:
[04/07/2023, 10:43:53] Error: The module '/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at bindings (/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/lib/linux.js:2:36)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/lib/index.js:14:22)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)


**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 1.6.0
* **Node.js Version**: 18.16.0
* **NPM Version**: 9.5.1
* **Operating System**: Raspbian GNU/Linux Buster (10)

**Comment by traviswparker** [comment]
I don’t think this is an issue with the Wyze plugin. Error references a dependency of the zigbee-nt plugin.

Either uninstall and reinstall that plugin to refresh dependencies or try 
`hb-service update-node` 
and 
`hb-service rebuild —-all`

**Comment by vascott1** [comment]
Will take a look but that plug in should not be activate and reverting the Wyze plugin resolved the issue. Seems something odd is happening. Not sure what yet.
  
  
  
  
  
  
  

  
  
>

**Comment by traviswparker** [comment]
I can’t do much with the zigbee-nt plugin because I don’t have the hardware, but I can install it and set the serial port to /dev/null so it will at least start. It gives an error about not being able to open the port as expected, but it constantly retries and the rest of homebridge runs, so the serialport dependency is no longer broken. 

That means it should work if you install/update it after updating to the current version of the Wyze plugin.

This is using docker-homebridge. I don’t know if your install maintains a copy of each plugin’s dependencies in the plugin’s directory, but the docker container does to avoid conflicts.

**Comment by sseller** [comment]
Just tried 0.5.29 and this is what I got and it puts homebridge in a boot loop. I have uninstalled the zigbee-nt plugin since that was suspected earlier. Agin, dropping back down to 0.5.24 and restarting homebridge resolves the issue. This is so weird!

[05/07/2023, 10:02:51] Homebridge v1.6.0 (HAP v0.11.0) (homebridge-ring) is running on port 44930.
[05/07/2023, 10:02:51] TypeError: Cannot read properties of undefined (reading 'device_id')
    at WyzeHMS.getHmsID (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:600:92)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WyzeHMS.updateCharacteristics (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeHMS.js:30:9)
    at WyzeHMS.update (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:351:7)
[05/07/2023, 10:02:51] Got SIGTERM, shutting down Homebridge...
[05/07/2023, 10:02:51] Got SIGTERM, shutting down child bridge process...
[05/07/2023, 10:02:51] Got SIGTERM, shutting down child bridge process...

**Comment by vascott1** [comment]
Just updated to 0.5.30. Here is what I am seeing. It seems that some thing with the Home Monitoring system. Just tried something. I excluded the HMS by Mac address and Boom! Success. I would not mind having my water sensors in HomeKit of course but this gets me closer and finally I have my wall switches. Is there anything I can supply that might help resolve this? This was the reason I stayed on 0.5.24 for so long. No support in that version for HMS.

[06/07/2023, 21:18:52] TypeError: Cannot read properties of undefined (reading 'device_id')
    at WyzeHMS.getHmsID (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:574:92)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WyzeHMS.updateCharacteristics (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeHMS.js:30:9)
    at WyzeHMS.update (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:371:7)

**Comment by jfarmer08** [comment]
Do you have HMS from wyze

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vascott1** [comment]
I have the Sense Hub. That is the base for the HMS system. As far as having the actual service, no. I only have the hub to be able to use the water sensors.
  

  
I guess I conflated the two. Sorry if that was confusing.   
  

  
Still, excluding the hub by max address fixed the issue I noted below.   
  
  
  
  
  
  
  

  
  
>

**Comment by jfarmer08** [comment]
Ok, So kind of making more sense. I am making a call `get_plan_binding_list_by_user` to be able to get info about the HUB. Since you don't have service, maybe you also don't have a plan. So this call is null on the return and throws everything off. 


Is the issue with NODE Module corrected?

**Comment by sseller** [comment]
That is correct. I do not have a plan. Thanks for checking it out. If that is ever “fixed” to allow no plan I will try removing my exclude.

Yes the NODE issue is resolved. I think that was a bit of a Red Herring.
