### ISSUE TITLE
Issue with update 0.5.32

### ISSUE THREAD

**Issue by kris1254** [jfarmer08/homebridge-wyze-smart-home#120]
**Describe The Bug:**
Reboot loop cause by bridged accessory query

**To Reproduce:**
Updated to newest version and it cannot start up, needed to fall back to 0.5.30

**Expected behavior:**
Normal operation

**Logs:**

[16/07/2023,
17:54:33] [Wyze] Launched child bridge with PID 4982
[16/07/2023, 17:54:33] Registering platform 'homebridge-wyze-smart-home.WyzeSmartHome"
[16/07/2023, 17:54:33] [Wyze] Loaded homebridge-wyze-smart-home v0.5.33 child bridge successfully
[16/07/2023, 17:54:33] Loaded 42 cached accessories from cachedAccessories.05D5C8212B4.
Error: Cannot find the bridged Accessory to remove.
at Bridge.Accessory. removeBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules /hap-node js/src/lib/Accessory.ts:717:13)
at Bridge.Accessory. removeBridgedAccessories (/usr/local/lib/node_modules /homebridge/node_modules /hap-no dejs/src/lib/Accessory.ts:733:12)
at BridgeService. handleUnregisterPlatformAccessories (/usr/local/lib/node_modules /homebridge/src/bridges ervice.ts: 404:17 )
at HomebridgeAPI.emit (node: events: 513:28)
at HomebridgeAPI.unregisterPlatformAccessories(/usr/local/lib/node_modules/homebridge/src/api.ts:355:10
Homebridge
Up To Date
V1.6.1
Homebridge
Running on port xxx
at WyzeSmartHome.configureAccessory (/usr/local/lib/ node_modules /homebridge-wyze-smart-home/src/wyzeSmar tHome. js: 217: 16 )
at /usr/local/lib/node modules /homebridge/src/bridgeService.ts:328:25 at
Array.filter (<anonymous>)
at BridgeService.restoreCachedPlatformAccessories(/usr/local/lib/nodemodules/homebridge/sr/bridgeServ ice.ts:288:69 )
at
ChildBridgeFork.startBridge(/usr/local/lib/node modules /homebridge/src/childBridgeFork.ts:186:24
[16/07/2023, 17:54:33] [wyze] Child bridge process ended
[16/07/2023, 17:54:33] [Wyze] Process Ended. Code: 1, Signal: null

**Plugin Config:**

{
    "bridge": {
        "name": "Homebridge 7469",
        "username": "xxx",
        "port": xxx,
        "pin": "xxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": xxx,
            "auth": "none",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Wyze",
            "username": "xxx",
            "password": "xxx",
            "refreshInterval": 60000,
            "entryExitDelay": 30,
            "mfaCode": "xxxx",
            "showAdvancedOptions": true,
            "excludeMacAddress": false,
            "excludedeviceType": true,
            "filterDeviceTypeList": [
                "Lock"
            ],
            "_bridge": {
                "username": "xxx",
                "port": xxx
            },
            "platform": "WyzeSmartHome"
        },
        {
            "name": "WizSmarthome",
            "enableScenes": false,
            "lastStatus": false,
            "refreshInterval": 0,
            "devices": [
                {
                    "host": "xxx",
                    "name": "wiz_b19bf5",
                    "mac": "xxxx"
                }
            ],
            "_bridge": {
                "username": "xxxxx",
                "port": xxxx
            },
            "platform": "WizSmarthome"
        }
    ]
}

**Environment:**

* **Plugin Version**: 0.5.32
* **Homebridge Version**:  1.6.1
* **Node.js Version**:  18.16.0
* **NPM Version**:  9.5.1
* **Operating System**: 
Raspbian GNU/Linux Bullseye (11)
--

**Comment by jfarmer08** [comment]
@kris1254  This seems that the plugin is trying to remove cache accessory and cannot. You can clear your cache manually and try again. Or you can try to upgrade again and turn on logging so that I can see what it's trying to remove.

**Comment by kris1254** [comment]
Thanks @jfarmer08 , I updated again and this solved my issue

**Comment by jfarmer08** [comment]
Can this issue be closed?
