### ISSUE TITLE
Cannot upgrade pass v0.5.24 with Wyze Lock error

### ISSUE THREAD

**Issue by metaesapuet** [jfarmer08/homebridge-wyze-smart-home#121]
**Describe The Bug:**
I run 3x Wyze Locks and the plugin works fine on v0.5.24
Running an update above v0.5.24+, the plugin just loops

**To Reproduce:**
running Wyze plugin above v0.5.24 with Wyze lock
Also tried setting it on "Exclude", error still persists

**Expected behavior:**
Plugin should run fine

**Logs:**

[Wyze] Request config: {"method":"POST","url":"app/v2/home_page/get_object_list","data":{"access_token":"xxxx","app_name":"com.hualai.WyzeCam","app_ver":"wyze_developer_api","app_version":"wyze_developer_api","phone_id":"wyze_developer_api","phone_system_type":"1","sc":"wyze_developer_api","sv":"wyze_developer_api","ts":1689615832169},"baseURL":"https://api.wyzecam.com"}
[7/17/2023, 1:43:52 PM] [Wyze] API response: [object Object]

/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:388
          this.homeKitAccessory.context.device_params.onoff_line = lockProperties[prop]
                                                                 ^
TypeError: Cannot set properties of undefined (setting 'onoff_line')
    at WyzeLock.lockGetProperty (/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:388:66)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Wyze] Child bridge process ended
[Wyze] Process Ended. Code: 1, Signal: null

**Plugin Config:**

{
    "name": "Wyze",
    "username": "xxxxx",
    "password": "xxxxx",
    "mfaCode": "xxxxx",
    "keyId": "xxxxx",
    "apiKey": "xxxxx",
    "refreshInterval": 60000,
    "entryExitDelay": 30,
    "showAdvancedOptions": true,
    "logging": "debug",
    "excludeMacAddress": false,
    "excludedeviceType": true,
    "filterDeviceTypeList": [
        "Light",
        "MeshLight",
        "LightStrip",
        "ContactSensor",
        "MotionSensor",
        "Lock",
        "TemperatureHumidity",
        "LeakSensor",
        "Camera",
        "Common",
        "S1Gateway"
    ],
    "_bridge": {
        "username": "0E:E7:C7:CA:3B:43",
        "port": 56933
    },
    "platform": "WyzeSmartHome"
}

**Screenshots:**

**Environment:**

* **Plugin Version**:  v0.5.25+
* **Homebridge Version**: v1.6.1
* **Node.js Version**: v18.16.1
* **NPM Version**: 
* **Operating System**: docker - Ubuntu Jammy Jellyfish (22.04.2 LTS)

**Comment by jfarmer08** [comment]
Do you have any other logs to share?

**Comment by metaesapuet** [comment]
> Do you have any other logs to share?

This just loops on any version above x0.5.24

[7/18/2023, 1:33:45 PM] [Wyze] Restarting Process...
[7/18/2023, 1:33:45 PM] [Wyze] Launched child bridge with PID 55434
[7/18/2023, 1:33:45 PM] Registering platform 'homebridge-wyze-smart-home.WyzeSmartHome'
[7/18/2023, 1:33:45 PM] [Wyze] Loaded homebridge-wyze-smart-home v0.5.34 child bridge successfully
[7/18/2023, 1:33:45 PM] Loaded 25 cached accessories from cachedAccessories.0EE7C7CA3B43.
[7/18/2023, 1:33:45 PM] [Wyze] [WyzePlug] Fetching status of "TBD 05"
[7/18/2023, 1:33:45 PM] [Wyze] [WyzePlug] Retrieving previous service for "TBD 05"
[7/18/2023, 1:33:45 PM] [Wyze] [WyzePlug] Fetching status of "TBD 04"
[7/18/2023, 1:33:45 PM] [Wyze] [WyzePlug] Retrieving previous service for "TBD 04"
[7/18/2023, 1:33:45 PM] [Wyze] Refreshing devices...
[7/18/2023, 1:33:45 PM] Homebridge v1.6.1 (HAP v0.11.1) (Wyze) is running on port 56933.
[7/18/2023, 1:33:45 PM] [Wyze] Request config: {"method":"POST","url":"app/v2/home_page/get_object_list","data":{"access_token":"xxxx","app_name":"com.hualai.WyzeCam","app_ver":"wyze_developer_api","app_version":"wyze_developer_api","phone_id":"wyze_developer_api","phone_system_type":"1","sc":"wyze_developer_api","sv":"wyze_developer_api","ts":1689701625769},"baseURL":"https://api.wyzecam.com"}
[7/18/2023, 1:33:46 PM] [Wyze] API response: [object Object]

/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:364
          this.homeKitAccessory.context.device_params.onoff_line = lockProperties[prop]
                                                                 ^
TypeError: Cannot set properties of undefined (setting 'onoff_line')
    at WyzeLock.lockGetProperty (/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:364:66)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/18/2023, 1:33:46 PM] [Wyze] Child bridge process ended
[7/18/2023, 1:33:46 PM] [Wyze] Process Ended. Code: 1, Signal: null

**Comment by metaesapuet** [comment]
> Which Lock do you have?

The Wyze Lock + Gateway.
https://www.wyze.com/products/wyze-lock
I guess the "1st gen"

**Comment by jfarmer08** [comment]
Also, you might try clearing your Cache - A lot has changed since that version. When you exclude the lock you still get this error?

**Comment by metaesapuet** [comment]
Uninstalling, reinstalling and reconfiguring the plugin works. Error seems to be tied to the existing bridge.
Just wish I didn't have to readd and reconfigure 21 Wyze plugs back into homekit and all their automations :(
