### ISSUE TITLE
New error this morning and homebridge in loop

### ISSUE THREAD

**Issue by iamvidoq** [jfarmer08/homebridge-wyze-smart-home#131]
**Describe Your Problem:**
Last night our eero network updated and this morning I noticed my wyze devices are disconnected in homekit. They work in the wyze app and our wyze sense v2 bridge is working fine. But Homebridge keeps restarting itself. At first I thought I needed to add the Wyze API Key which I hadn't done before but I'm still getting the error. Disabling this plugin stops the problem. One thought. Since it's saying "security system current state" could It be that I turned off monitoring this morning? I didn't want it but was the only way to get the sense v2 bridge (paying for one month). I did the thing in the app this morning that erased the monitoring setup on it (it still functions as a bridge for the sensors).

**Logs:**

[27/07/2023, 11:15:11] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge B935) is running on port 51697.
[27/07/2023, 11:15:12] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'Security System Current State': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[27/07/2023, 11:15:12] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[27/07/2023, 11:15:13] TypeError: Cannot read properties of undefined (reading 'device_id')
    at WyzeHMS.getHmsID (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:529:92)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WyzeHMS.updateCharacteristics (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeHMS.js:30:9)
    at WyzeHMS.update (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:326:7)
[27/07/2023, 11:15:13] Got SIGTERM, shutting down Homebridge...
[27/07/2023, 11:15:16] [Nest] initing home_away_sensor XXXXXX
[27/07/2023, 11:15:16] [Nest] initing protect XXXXXX
[27/07/2023, 11:15:16] [Nest] initing protect XXXXXX
[27/07/2023, 11:15:16] [Nest] initing protect XXXXXX
[27/07/2023, 11:15:16] [Nest] initing protect XXXXXX
[27/07/2023, 11:15:16] [Nest] initing protect XXXXXX
[27/07/2023, 11:15:18] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[27/07/2023, 11:15:23] [HB Supervisor] Restarting Homebridge...
[27/07/2023, 11:15:23] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[27/07/2023, 11:15:23] [HB Supervisor] Started Homebridge v1.6.1 with PID: 13355
[27/07/2023, 11:15:25] Loaded config.json with 2 accessories and 3 platforms.

**Plugin Config:**

{
    "name": "Wyze",
    "username": "jcmcnamee@gmail.com",
    "password": "AtF4P4xHko3TDr67jatGtbTBM$Hxr28o8,9yfuqKiup$gFb4md",
    "keyId": "983549db-8f36-4f74-bfcd-d5d19e4d1a15",
    "apiKey": "MGLUnVRSEuEbXkC75Ed7ti4QnGMIICGpV3bjQdbZ70uiQKMowPzft09DbbCC",
    "mfaCode": "337162",
    "refreshInterval": 60000,
    "entryExitDelay": 30,
    "showAdvancedOptions": true,
    "logging": "none",
    "excludeMacAddress": false,
    "excludedeviceType": true,
    "filterDeviceTypeList": [
        "Camera"
    ],
    "platform": "WyzeSmartHome"
}

**Screenshots:**

None

**Environment:**

* **Plugin Version**: 0.5.36
* **Homebridge Version**: 1.6.1
* **Node.js Version**: 18.17.0
* **NPM Version**: n/a?
* **Operating System**: Raspbian

**Comment by jfarmer08** [comment]
Can you upgrade to the latest and enable debug logging?

**Comment by jfarmer08** [comment]
Never mind you don't have to upgrade. Just exclude S1Gateway.

**Comment by iamvidoq** [comment]
Oh good point...that worked. Thanks!
