### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'onoff_line')

### ISSUE THREAD

**Issue by littleferris** [jfarmer08/homebridge-wyze-smart-home#138]
**Describe The Bug:**

Recently updated ther version I cant remember from what version but I get this error now and it is not in a loop of ending and restarting with that error. 

```
/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:364
          this.homeKitAccessory.context.device_params.onoff_line = lockProperties[prop]
                                                                 ^
TypeError: Cannot set properties of undefined (setting 'onoff_line')
    at WyzeLock.lockGetProperty (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:364:66)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[09/08/2023, 09:13:35] [Wyze] Child bridge process ended
```

**To Reproduce:**

updated to version v0.5.36 and downgrading doesnt seem to fix the issue.

**Expected behavior:**

bridge not to end
**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```
```
[09/08/2023, 09:34:00] [Wyze] Restarting Process...
[09/08/2023, 09:34:02] [Wyze] Launched child bridge with PID 5076
[09/08/2023, 09:34:02] Registering platform 'homebridge-wyze-smart-home.WyzeSmartHome'
[09/08/2023, 09:34:02] [Wyze] Loaded homebridge-wyze-smart-home v0.5.36 child bridge successfully
[09/08/2023, 09:34:02] Loaded 12 cached accessories from cachedAccessories.0E5141D49424.
[09/08/2023, 09:34:02] [Wyze] Camera (Model: GW_BE1 (Mac: undefined (Name: undefined) not supported submit a request to https://github.com/jfarmer08/homebridge-wyze-smart-home/issues to have it added. If no issues are found
[09/08/2023, 09:34:02] Homebridge v1.6.1 (HAP v0.11.1) (Wyze) is running on port 55039.

/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:364
          this.homeKitAccessory.context.device_params.onoff_line = lockProperties[prop]
                                                                 ^
TypeError: Cannot set properties of undefined (setting 'onoff_line')
    at WyzeLock.lockGetProperty (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:364:66)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[09/08/2023, 09:34:03] [Wyze] Child bridge process ended

```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.

{
    "name": "Wyze",
    "username": "@gmail.com",
    "password": "pswd",
    "keyId": " removed",
    "apiKey": "removed",
    "mfaCode": "removed",
    "refreshInterval": 5000,
    "entryExitDelay": 30,
    "showAdvancedOptions": true,
    "logging": "debug",
    "excludeMacAddress": false,
    "excludedeviceType": false,
    "_bridge": {
        "username": "rem oved",
        "port": 55039
    },
    "platform": "WyzeSmartHome"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**:  1.6.1
* **Node.js Version**: 18.16.0
* **NPM Version**: 8.19.4
* **Operating System**:  raspbian

**Comment by jfarmer08** [comment]
Can you exclude the camera and try again?

**Comment by littleferris** [comment]
so that camera error that shows up is the doorbell pro I think. But the error that I am getting I think is related to the lock not the camera. I Did try to exclude both just in case and nothing changed.

**Comment by jfarmer08** [comment]
Can you exlcude the lock and then clear your cache?

**Comment by littleferris** [comment]
I did absolutely nothing and the error is gone and I cant get it to come back, so idk what is going on.
