### ISSUE TITLE
Cannot read properties of undefined (reading 'device_id')

### ISSUE THREAD

**Issue by sanchogeorgek** [jfarmer08/homebridge-wyze-smart-home#142]
**Describe Your Problem:**
Running into errors starting the child bridge. Appears to be an issue reading a device list returned from Wyze.

**Logs:**

```
[8/19/2023, 12:08:58 AM] [Wyze] Launched child bridge with PID 1279
[8/19/2023, 12:08:59 AM] Registering platform 'homebridge-wyze-smart-home.WyzeSmartHome'
[8/19/2023, 12:08:59 AM] [Wyze] Loaded homebridge-wyze-smart-home v0.5.36 child bridge successfully
[8/19/2023, 12:08:59 AM] Loaded 3 cached accessories from cachedAccessories.0E16E98AD398.
[8/19/2023, 12:08:59 AM] [Wyze] Camera (Model: GW_BE1 (Mac: undefined (Name: undefined) not supported submit a request to https://github.com/jfarmer08/homebridge-wyze-smart-home/issues to have it added. If no issues are found
[8/19/2023, 12:08:59 AM] Homebridge v1.6.1 (HAP v0.11.1) (Wyze) is running on port 40914.
[8/19/2023, 12:09:00 AM] [Wyze] Camera (Model: GW_BE1 (Mac: GW_BE1_7C78B2A184F3 (Name: Foyer Doorbell) not supported submit a request to https://github.com/jfarmer08/homebridge-wyze-smart-home/issues to have it added. If no issues are found

/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:529
        this.homeKitAccessory.context.device_params.hmsId = response.data[0].deviceList[0].device_id
                                                                                           ^
TypeError: Cannot read properties of undefined (reading 'device_id')
    at WyzeHMS.getHmsID (/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:529:92)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WyzeHMS.updateCharacteristics (/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeHMS.js:30:9)
    at WyzeHMS.update (/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:326:7)
[8/19/2023, 12:09:00 AM] [Wyze] Child bridge process ended
[8/19/2023, 12:09:00 AM] [Wyze] Process Ended. Code: 1, Signal: null
[8/19/2023, 12:09:07 AM] [Wyze] Restarting Process...
```

**Plugin Config:**

```json
        {
            "name": "Wyze",
            "username": "****@****.com",
            "password": "******",
            "keyId": "*****",
            "apiKey": "*****",
            "refreshInterval": 60000,
            "entryExitDelay": 30,
            "showAdvancedOptions": true,
            "logging": "none",
            "excludeMacAddress": false,
            "excludedeviceType": true,
            "filterDeviceTypeList": [
                "Camera"
            ],
            "_bridge": {
                "username": "0E:16:E9:8A:D3:98",
                "port": 40914
            },
            "platform": "WyzeSmartHome"
        }
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 0.5.36
* **Homebridge Version**: 1.6.1
* **Node.js Version**: 18.16.0
* **NPM Version**: 9.5.1
* **Operating System**: Docker

**Comment by jfarmer08** [comment]
Exclude S1Gateway. Looks like you don't pay for HMS

**Comment by sanchogeorgek** [comment]
Ah. I do have HMS sub but recently reset my sense hub and didn’t quite get to adding any security devices before using the plugin in homebridge.

**Comment by sanchogeorgek** [comment]
Closing issue. 

Resolution:  Exclude S1Gateway in plugin config as illustrated below or add at least one security device to sense home monitoring hub

```json
"filterDeviceTypeList": [
                "Camera"
            ]
```
