### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by kentd227** [jfarmer08/homebridge-wyze-smart-home#147]
The Wyze plug in works for about 10 minutes then I keep getting the following error: 

Error: AccessTokenError
    at WyzeAPI._performRequest (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/wyz-api/index.js:128:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WyzeAPI.request (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/wyz-api/index.js:75:14)
    at WyzeAPI.getObjectList (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/wyz-api/index.js:232:20)
    at WyzeSmartHome.refreshDevices (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:96:26)
    at WyzeSmartHome.runLoop (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:85:9)

I've created a key ID and an API and entered those into the log in information, but I still get this error after about 10 minutes of everything working fine.  Any advice would be welcome. Thanks

**Comment by genotrance** [comment]
I have the same issue and my locks don't work anymore. I have tried many older versions but it refuses to work. I have added an API key.

```
[9/15/2023, 7:15:54 PM] [Wyze] Launched child bridge with PID 3651
[9/15/2023, 7:15:54 PM] Registering platform 'homebridge-wyze-smart-home.WyzeSmartHome'
[9/15/2023, 7:15:54 PM] [Wyze] Loaded homebridge-wyze-smart-home v0.5.36 child bridge successfully
[9/15/2023, 7:15:54 PM] Loaded 3 cached accessories from cachedAccessories.0E28XXXXXXX.
[9/15/2023, 7:15:54 PM] Homebridge v1.6.1 (HAP v0.11.1) (Wyze) is running on port 12345.
[9/15/2023, 7:15:55 PM] [Wyze] Error: AccessTokenError
    at WyzeAPI._performRequest (/homebridge/node_modules/homebridge-wyze-smart-home/src/wyz-api/index.js:128:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WyzeAPI.request (/homebridge/node_modules/homebridge-wyze-smart-home/src/wyz-api/index.js:75:14)
    at WyzeAPI.getObjectList (/homebridge/node_modules/homebridge-wyze-smart-home/src/wyz-api/index.js:232:20)
    at WyzeSmartHome.refreshDevices (/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:96:26)
    at WyzeSmartHome.runLoop (/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:85:9)
[9/15/2023, 7:15:55 PM] [Wyze] Error, refreshing access token and trying again

/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:359
    const prop_key = Object.keys(lockProperties)
                            ^
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at WyzeLock.lockGetProperty (/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:359:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[9/15/2023, 7:15:55 PM] [Wyze] Child bridge process ended
[9/15/2023, 7:15:55 PM] [Wyze] Process Ended. Code: 1, Signal: null
```

**Comment by jfarmer08** [comment]
Can you confirm what version you are using?

**Comment by genotrance** [comment]
I just upgraded to 0.5.37-alpha.1 and still see the issue.

```
[9/27/2023, 1:50:30 PM] [Wyze] Launched child bridge with PID 1334
[9/27/2023, 1:50:30 PM] Registering platform 'homebridge-wyze-smart-home.WyzeSmartHome'
[9/27/2023, 1:50:30 PM] [Wyze] Loaded homebridge-wyze-smart-home v0.5.37-alpha.1 child bridge successfully
[9/27/2023, 1:50:30 PM] Loaded 3 cached accessories from cachedAccessories.0E28XXXXXXX.
[9/27/2023, 1:50:30 PM] Homebridge v1.6.1 (HAP v0.11.1) (Wyze) is running on port 35867.

/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:366
          this.homeKitAccessory.context.device_params.onoff_line = lockProperties[prop]
                                                                 ^
TypeError: Cannot set properties of undefined (setting 'onoff_line')
    at WyzeLock.lockGetProperty (/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:366:66)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[9/27/2023, 1:50:30 PM] [Wyze] Child bridge process ended
[9/27/2023, 1:50:30 PM] [Wyze] Process Ended. Code: 1, Signal: null
```

My HomeBridge version is v1.6.1.

**Comment by jfarmer08** [comment]
Can you try 0.5.37-alpha.5 and see if you still have an issue?

**Comment by jfarmer08** [comment]
Any update?

**Comment by kentd227** [comment]
Sorry for the delay! The API issue stopped! Thanks for your help. On Nov 6, 2023, at 2:17 PM, Farmer ***@***.***> wrote:﻿
Any update?

**Comment by genotrance** [comment]
Fixed for me too!
