### ISSUE TITLE
No Accesories working, child process has ended boot loop. Code 1 signal null

### ISSUE THREAD

**Issue by Ceeefoe** [jfarmer08/homebridge-wyze-smart-home#169]
Currently having issues with this plugin for my Wyze Accesories seemingly out of nowhere. No settings were changed and I was running this plugin for over a month flawlessly. 

All of my accessories are showing as no response and they do not show in homebridge. There’s a boot loop the plug in keep going through shown below. 

I’ve tried changing API Key and removing and reinstall bridge to HomeKit to no avail. Appreciate any help. Thank you

**Logs:**
                                           ^
TypeError: Cannot read properties of undefined (reading 'plugin')
    at WyzeLight.updateCharacteristics (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeLight.js:29:44)
    at WyzeLight.update (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:336:18)
    at WyzeSmartHome.loadDevice (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:155:17)
    at WyzeSmartHome.loadDevices (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:115:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WyzeSmartHome.refreshDevices (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:104:7)
    at WyzeSmartHome.runLoop (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:88:9)
[02/10/2023, 16:37:54] [Wyze] Child bridge process ended
[02/10/2023, 16:37:54] [Wyze] Process Ended. Code: 1, Signal: null
[02/10/2023, 16:38:01] [Wyze] Restarting Process...
[02/10/2023, 16:38:03] [Wyze] Launched child bridge with PID 17630
[02/10/2023, 16:38:04] Registering platform 'homebridge-wyze-smart-home.WyzeSmartHome'
[02/10/2023, 16:38:04] [Wyze] Loaded homebridge-wyze-smart-home v0.5.37-alpha.2 child bridge successfully
[02/10/2023, 16:38:04] Loaded 9 cached accessories from cachedAccessories.0E2439B9BDA6.
[02/10/2023, 16:38:04] Homebridge v1.6.1 (HAP v0.11.1) (Wyze) is running on port 58690.

/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeLight.js:29
      const propertyList = await this.this.plugin.client.getDevicePID(this.mac, this.product_model)

**Comment by jfarmer08** [comment]
Not enough information or logs to determine the issue.

**Comment by Ceeefoe** [comment]
> Not enough information or logs to determine the issue.

Thanks for responding, what other information can I provide to help diagnose this? The attached log is the only thing I am seeing.

**Comment by taylerc** [comment]
I am having the same issue. I updated to the latest version of the plugin (v0.5.37-alpha.2) and immediately started on a boot loop with the below logs. 

After reverting back to v0.5.36, the issue cleared up and everything is working again. 

TypeError: Cannot read properties of undefined (reading 'plugin')
    at WyzeLight.updateCharacteristics (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeLight.js:29:44)
    at WyzeLight.update (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:336:18)
    at WyzeSmartHome.loadDevice (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:155:17)
    at WyzeSmartHome.loadDevices (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:115:36)
    at WyzeSmartHome.refreshDevices (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:104:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WyzeSmartHome.runLoop (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:88:9)
[03/10/2023, 17:49:10] TypeError: Cannot read properties of undefined (reading 'plugin')
    at WyzeLight.updateCharacteristics (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeLight.js:29:44)
    at WyzeLight.update (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:336:18)
    at WyzeSmartHome.loadDevice (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:155:17)
    at WyzeSmartHome.loadDevices (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:115:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WyzeSmartHome.refreshDevices (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:104:7)
    at WyzeSmartHome.runLoop (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:88:9)
[03/10/2023, 17:49:10] Got SIGTERM, shutting down Homebridge...

**Comment by Ceeefoe** [comment]
> I am having the same issue. I updated to the latest version of the plugin (v0.5.37-alpha.2) and immediately started on a boot loop with the below logs.
> 
> After reverting back to v0.5.36, the issue cleared up and everything is working again.
> 
> TypeError: Cannot read properties of undefined (reading 'plugin') at WyzeLight.updateCharacteristics (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeLight.js:29:44) at WyzeLight.update (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:336:18) at WyzeSmartHome.loadDevice (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:155:17) at WyzeSmartHome.loadDevices (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:115:36) at WyzeSmartHome.refreshDevices (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:104:18) at processTicksAndRejections (node:internal/process/task_queues:95:5) at WyzeSmartHome.runLoop (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:88:9) [03/10/2023, 17:49:10] TypeError: Cannot read properties of undefined (reading 'plugin') at WyzeLight.updateCharacteristics (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeLight.js:29:44) at WyzeLight.update (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:336:18) at WyzeSmartHome.loadDevice (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:155:17) at WyzeSmartHome.loadDevices (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:115:36) at processTicksAndRejections (node:internal/process/task_queues:95:5) at WyzeSmartHome.refreshDevices (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:104:7) at WyzeSmartHome.runLoop (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:88:9) [03/10/2023, 17:49:10] Got SIGTERM, shutting down Homebridge...

Thanks for posting, I reverted back to v0.5.36 and it fixed the issue as well.

**Comment by gregj5** [comment]
I had this same issue.  The problem is this line of code contained in WyzeLight.js
const propertyList = await this.this.plugin.client.getDevicePID(this.mac, this.product_model)

I removed the extra "this" and it started working again.  
const propertyList = await this.plugin.client.getDevicePID(this.mac, this.product_model)

On my particular system the location for this file was here:
/mnt/user/appdata/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories#

**Comment by jfarmer08** [comment]
Thank you. I will get this fixed.

**Comment by gregj5** [comment]
Happy to help.  Thanks for an awesome plugin!

**Comment by ExioStar** [comment]
Was looking for this! Had this exact issue and reverting to v0.5.36 worked for me too. I had the latest alpha working for a few days, but restarting the server made it loop again.

**Comment by jfarmer08** [comment]
Update released.

**Comment by DiscoveryOV** [comment]
I am seeing this loop on v0.5.37-alpha.3.

```[10/11/2023, 11:15:42 PM] Loaded 15 cached accessories from cachedAccessories.0EA7E2735338.
Error: Cannot find the bridged Accessory to remove.
    at Bridge.Accessory.removeBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:717:13)
    at Bridge.Accessory.removeBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:733:12)
    at BridgeService.handleUnregisterPlatformAccessories (/usr/lib/node_modules/homebridge/src/bridgeService.ts:404:17)
    at HomebridgeAPI.emit (node:events:513:28)
    at HomebridgeAPI.unregisterPlatformAccessories (/usr/lib/node_modules/homebridge/src/api.ts:355:10)
    at WyzeSmartHome.configureAccessory (/usr/lib/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:248:16)
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:328:25
    at Array.filter (<anonymous>)
    at BridgeService.restoreCachedPlatformAccessories (/usr/lib/node_modules/homebridge/src/bridgeService.ts:288:69)
    at ChildBridgeFork.startBridge (/usr/lib/node_modules/homebridge/src/childBridgeFork.ts:186:24)
[10/11/2023, 11:15:43 PM] [Wyze] Child bridge process ended
[10/11/2023, 11:15:43 PM] [Wyze] Process Ended. Code: 1, Signal: null```

**Comment by DiscoveryOV** [comment]
Removing all cached accessories seems to have resolved this issue, but now my Wyze Color V2 bulbs are no longer available.

**Comment by jfarmer08** [comment]
What model are those?

**Comment by jfarmer08** [comment]
https://github.com/jfarmer08/homebridge-wyze-smart-home/releases/tag/v0.5.37-alpha.4
