### ISSUE TITLE
New Light Bulb

### ISSUE THREAD

**Issue by lonniemmercer** [jfarmer08/homebridge-wyze-smart-home#170]
Can you please add support for new light bulb HL_A19C2?  It has my plugin in a boot loop because it doesn’t recognize it yet.  Thanks!

**Comment by jfarmer08** [comment]
Can you upload logs

**Comment by lonniemmercer** [comment]
I can try but I have like 15 of them, below are the logs:


10/11/2023, 9:35:06 PM] [Wyze] Child bridge process ended
[10/11/2023, 9:35:06 PM] [Wyze] Process Ended. Code: 1, Signal: null
[10/11/2023, 9:35:13 PM] [Wyze] Restarting Process...
[10/11/2023, 9:35:13 PM] [Wyze] Launched child bridge with PID 1799124
[10/11/2023, 9:35:14 PM] Registering platform 'homebridge-wyze-smart-home.WyzeSmartHome'
[10/11/2023, 9:35:14 PM] [Wyze] Loaded homebridge-wyze-smart-home v0.5.37-alpha.3 child bridge successfully
[10/11/2023, 9:35:14 PM] Loaded 42 cached accessories from cachedAccessories.0E74236F9793.
[10/11/2023, 9:35:14 PM] [Wyze] MeshLight (Model: HL_A19C2 (Mac: undefined (Name: undefined) not supported submit a request to https://github.com/jfarmer08/homebridge-wyze-smart-home/issues to have it added. If no issues are found
Error: Cannot find the bridged Accessory to remove.
    at Bridge.Accessory.removeBridgedAccessory (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:717:13)
    at Bridge.Accessory.removeBridgedAccessories (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:733:12)
    at BridgeService.handleUnregisterPlatformAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:404:17)
    at HomebridgeAPI.emit (node:events:514:28)
    at HomebridgeAPI.unregisterPlatformAccessories (/var/lib/homebridge/node_modules/homebridge/src/api.ts:355:10)
    at WyzeSmartHome.configureAccessory (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:248:16)
    at /var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:328:25
    at Array.filter (<anonymous>)
    at BridgeService.restoreCachedPlatformAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:288:69)
    at ChildBridgeFork.startBridge (/var/lib/homebridge/node_modules/homebridge/src/childBridgeFork.ts:186:24)
[10/11/2023, 9:35:14 PM] [Wyze] Child bridge process ended
[10/11/2023, 9:35:14 PM] [Wyze] Process Ended. Code: 1, Signal: null
[10/11/2023, 9:35:21 PM] [Wyze] Restarting Process...
[10/11/2023, 9:35:21 PM] [Wyze] Launched child bridge with PID 1799135
[10/11/2023, 9:35:22 PM] Registering platform 'homebridge-wyze-smart-home.WyzeSmartHome'
[10/11/2023, 9:35:22 PM] [Wyze] Loaded homebridge-wyze-smart-home v0.5.37-alpha.3 child bridge successfully
[10/11/2023, 9:35:22 PM] Loaded 42 cached accessories from cachedAccessories.0E74236F9793.
[10/11/2023, 9:35:22 PM] [Wyze] MeshLight (Model: HL_A19C2 (Mac: undefined (Name: undefined) not supported submit a request to https://github.com/jfarmer08/homebridge-wyze-smart-home/issues to have it added. If no issues are found
Error: Cannot find the bridged Accessory to remove.
    at Bridge.Accessory.removeBridgedAccessory (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:717:13)
    at Bridge.Accessory.removeBridgedAccessories (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:733:12)
    at BridgeService.handleUnregisterPlatformAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:404:17)
    at HomebridgeAPI.emit (node:events:514:28)
    at HomebridgeAPI.unregisterPlatformAccessories (/var/lib/homebridge/node_modules/homebridge/src/api.ts:355:10)
    at WyzeSmartHome.configureAccessory (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:248:16)
    at /var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:328:25
    at Array.filter (<anonymous>)
    at BridgeService.restoreCachedPlatformAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:288:69)
    at ChildBridgeFork.startBridge (/var/lib/homebridge/node_modules/homebridge/src/childBridgeFork.ts:186:24)
[10/11/2023, 9:35:22 PM] [Wyze] Child bridge process ended

**Comment by jfarmer08** [comment]
It's does not seem to report MAC address. Can you enable apilogging if your using alpha build.

**Comment by lonniemmercer** [comment]
Does this help?

[10/11/2023, 9:49:04 PM] [Wyze] Child bridge process ended
[10/11/2023, 9:49:04 PM] [Wyze] Process Ended. Code: 1, Signal: null
[10/11/2023, 9:49:11 PM] [Wyze] Restarting Process...
[10/11/2023, 9:49:11 PM] [Wyze] Launched child bridge with PID 1800932
[10/11/2023, 9:49:11 PM] Registering platform 'homebridge-wyze-smart-home.WyzeSmartHome'
[10/11/2023, 9:49:11 PM] [Wyze] Loaded homebridge-wyze-smart-home v0.5.37-alpha.3 child bridge successfully
[10/11/2023, 9:49:11 PM] Loaded 42 cached accessories from cachedAccessories.0E74236F9793.
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Fetching status of "Master Bedroom Fan"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Retrieving previous service for "Master Bedroom Fan"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Fetching status of "Master Bedroom Sconces"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Retrieving previous service for "Master Bedroom Sconces"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Fetching status of "Master Bath Shower"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Retrieving previous service for "Master Bath Shower"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Fetching status of "Master Bath Main"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Retrieving previous service for "Master Bath Main"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Fetching status of "LD_SS1_D03F27F09791"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Retrieving previous service for "LD_SS1_D03F27F09791"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Fetching status of "Master Bath Mirror"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Retrieving previous service for "Master Bath Mirror"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Fetching status of "LD_SS1_7C78B2FED43B"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Retrieving previous service for "LD_SS1_7C78B2FED43B"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Fetching status of "Wyze Switch"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Retrieving previous service for "Wyze Switch"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Fetching status of "Wyze Switch"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Retrieving previous service for "Wyze Switch"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Fetching status of "Wyze Switch"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Retrieving previous service for "Wyze Switch"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Fetching status of "Boys Room Fan"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Retrieving previous service for "Boys Room Fan"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Fetching status of "Living Door Foyer"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Retrieving previous service for "Living Door Foyer"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Fetching status of "Front Porch"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Retrieving previous service for "Front Porch"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Fetching status of "Living Room Fan"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Retrieving previous service for "Living Room Fan"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Fetching status of "Maelyn’s Room"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Retrieving previous service for "Maelyn’s Room"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Fetching status of "Wyze Switch"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Retrieving previous service for "Wyze Switch"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Fetching status of "Wyze Switch"
[10/11/2023, 9:49:12 PM] [Wyze] [WyzeSwitch] Retrieving previous service for "Wyze Switch"
[10/11/2023, 9:49:12 PM] [Wyze] MeshLight (Model: HL_A19C2 (Mac: undefined (Name: undefined) not supported submit a request to https://github.com/jfarmer08/homebridge-wyze-smart-home/issues to have it added. If no issues are found
Error: Cannot find the bridged Accessory to remove.
    at Bridge.Accessory.removeBridgedAccessory (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:717:13)
    at Bridge.Accessory.removeBridgedAccessories (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:733:12)
    at BridgeService.handleUnregisterPlatformAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:404:17)
    at HomebridgeAPI.emit (node:events:514:28)
    at HomebridgeAPI.unregisterPlatformAccessories (/var/lib/homebridge/node_modules/homebridge/src/api.ts:355:10)
    at WyzeSmartHome.configureAccessory (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:248:16)
    at /var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:328:25
    at Array.filter (<anonymous>)
    at BridgeService.restoreCachedPlatformAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:288:69)
    at ChildBridgeFork.startBridge (/var/lib/homebridge/node_modules/homebridge/src/childBridgeFork.ts:186:24)
[10/11/2023, 9:49:12 PM] [Wyze] Child bridge process ended
[10/11/2023, 9:49:12 PM] [Wyze] Process Ended. Code: 1, Signal: null
[10/11/2023, 9:49:19 PM] [Wyze] Restarting Process...

**Comment by jfarmer08** [comment]
No. I need to see the api requests. It will show what is in the return of getDevices(). 

What version are you using?

**Comment by jfarmer08** [comment]
https://github.com/jfarmer08/homebridge-wyze-smart-home/releases/tag/v0.5.37-alpha.4
