### ISSUE TITLE
Issue after update to alpha 4

### ISSUE THREAD

**Issue by lonniemmercer** [jfarmer08/homebridge-wyze-smart-home#179]
[10/14/2023, 12:19:12 PM] Homebridge v1.6.1 (HAP v0.11.1) (Wyze) is running on port 59112.

/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/node_modules/colorsys/colorsys.js:197
  return colorsys.rgb2Hsv(rgb.r, rgb.g, rgb.b)
                              ^
TypeError: Cannot read properties of null (reading 'r')
    at Object.colorsys.hex2Hsv (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/node_modules/colorsys/colorsys.js:197:31)
    at WyzeMeshLight.updateColor (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeMeshLight.js:71:31)
    at WyzeMeshLight.updateCharacteristics (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeMeshLight.js:52:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WyzeMeshLight.update (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:336:7)

**Comment by jfarmer08** [comment]
Sometimes the API does return Nulls. I will see what i can do to help this. You can try to change your color properties to fix this in the mean time

**Comment by jfarmer08** [comment]
Any update
