### ISSUE TITLE
Homebridge is forced to exit 

### ISSUE THREAD

**Issue by identd113** [jfarmer08/homebridge-wyze-smart-home#185]
**Describe The Bug:**
When initially loaded, this works as expected.  After sometime, Homebridge exits.

**To Reproduce:**
Add a camera, and turn it off via the Wyze app or via the newly added HomeKit switch

**Expected behavior:**
Any error should return a failed message to HomeKit, and not force Homebridge to exit

**Logs:**

```
[10/24/2023, 12:37:29 PM] [Wyze] Error: DeviceIsOffline
    at WyzeAPI._performRequest (/opt/homebrew/lib/node_modules/homebridge-wyze-smart-home/src/wyze-api/src/index.js:130:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WyzeAPI.request (/opt/homebrew/lib/node_modules/homebridge-wyze-smart-home/src/wyze-api/src/index.js:79:14)
    at WyzeAPI.runAction (/opt/homebrew/lib/node_modules/homebridge-wyze-smart-home/src/wyze-api/src/index.js:274:20)
    at WyzeAPI.cameraPrivacy (/opt/homebrew/lib/node_modules/homebridge-wyze-smart-home/src/wyze-api/src/index.js:782:56)
[10/24/2023, 12:37:29 PM] [Wyze] Error, refreshing access token and trying again
[10/24/2023, 12:37:29 PM] [Wyze] Error, logLevel in and trying again
[10/24/2023, 12:37:30 PM] Error: DeviceIsOffline
    at WyzeAPI._performRequest (/opt/homebrew/lib/node_modules/homebridge-wyze-smart-home/src/wyze-api/src/index.js:130:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WyzeAPI.runAction (/opt/homebrew/lib/node_modules/homebridge-wyze-smart-home/src/wyze-api/src/index.js:274:20)
    at WyzeAPI.cameraPrivacy (/opt/homebrew/lib/node_modules/homebridge-wyze-smart-home/src/wyze-api/src/index.js:782:56)
plexserver@woodflix .homebridge %    
```

**Plugin Config:**

```json
        {
           "platform": "WyzeSmartHome",
            "name": "Wyze",
            "username": "XXX@gmail.com",
            "password": "XXXXXXXX",
            "keyId": "xxxxxx-xxxx-xxxx-xxx-xxxxxxxx",
            "apiKey": "xxxxxxxxxxxxxx",
            "refreshInterval": 60000
        }
```

**Screenshots:**

**Environment:**

* **Plugin Version**: Since disabled, was homebridge-wyze-smart-home v0.5.37-alpha.5
* **Homebridge Version**: 1.6.1
* **Node.js Version**: v20.7.0
* **NPM Version**: 10.1.0
* **Operating System**: OSX 14

**Comment by jfarmer08** [comment]
@identd113  Can you check to make sure your camera is online before you try to turn it on?

**Comment by jfarmer08** [comment]
https://github.com/jfarmer08/homebridge-wyze-smart-home/releases/tag/v0.5.37-alpha.6

**Comment by identd113** [comment]
I believe the camera were all online, but I have one that is added to the account, but not currently power on.  I installed alpha-6, and will report back with any issues.

**Comment by jfarmer08** [comment]
The latest release should help.

**Comment by identd113** [comment]
I have installed this, and it seems to resolve the issues as reported.
