### ISSUE TITLE
TypeError: devices is not iterable

### ISSUE THREAD

**Issue by Geczy** [jfarmer08/homebridge-wyze-smart-home#221]
looks like a simple issue that needs a fix, not sure why it happened all of a sudden

```
[2/13/2024, 4:33:37 PM] [WyzeSmartHome] Error getting devices: TypeError: devices is not iterable
[2/13/2024, 4:34:38 PM] [WyzeSmartHome] Error getting devices: TypeError: devices is not iterable
[2/13/2024, 4:35:38 PM] [WyzeSmartHome] Error getting devices: TypeError: devices is not iterable
[2/13/2024, 4:36:38 PM] [WyzeSmartHome] Error getting devices: TypeError: devices is not iterable
[2/13/2024, 4:37:39 PM] [WyzeSmartHome] Error getting devices: TypeError: devices is not iterable
[2/13/2024, 4:38:39 PM] [WyzeSmartHome] Error getting devices: TypeError: devices is not iterable
[2/13/2024, 4:39:39 PM] [WyzeSmartHome] Error getting devices: TypeError: devices is not iterable
[2/13/2024, 4:39:40 PM] [Homebridge UI] Running Command: npm install --save homebridge-wyze-smart-home@0.5.44
[2/13/2024, 4:40:39 PM] [WyzeSmartHome] Error getting devices: TypeError: devices is not iterable
[2/13/2024, 4:41:40 PM] [WyzeSmartHome] Error getting devices: TypeError: devices is not iterable
```

**Comment by jfarmer08** [comment]
Did you change your password and apikeys at the same time

**Comment by jshuffield6772** [comment]
I'm having this problem as well.  Just set up homebridge, and the Wyze products worked for a day....

**Comment by BBfly1** [comment]
as soon as I updated from v0.5.42 to v0.5.44, I receive the similar messages ... result: fails API login

4/02/2024, 11:54:33] [Wyze] Initializing WyzeSmartHome platform...
[14/02/2024, 11:54:36] [Wyze] Error: Potentially recoverable error during request
    at WyzeAPI._performRequest (/usr/local/lib/node_modules/homebridge-wyze-smart-home/node_modules/wyze-api/src/index.js:150:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WyzeAPI.request (/usr/local/lib/node_modules/homebridge-wyze-smart-home/node_modules/wyze-api/src/index.js:86:14)
    at WyzeAPI.getObjectList (/usr/local/lib/node_modules/homebridge-wyze-smart-home/node_modules/wyze-api/src/index.js:304:20)
    at WyzeSmartHome.refreshDevices (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:102:26)
    at WyzeSmartHome.runLoop (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:91:9)
[14/02/2024, 11:54:36] [Wyze] Error, refreshing access token and trying again
[14/02/2024, 11:54:46] [Wyze] Error, logging in and trying again
[14/02/2024, 11:54:47] [Wyze] Request failed: AxiosError: Request failed with status code 400
...
rolled back to v0.5.42 but still get the error messages from that version ...

[14/02/2024, 12:18:26] [Wyze] Error getting devices: TypeError: devices is not iterable
[14/02/2024, 12:19:27] [Wyze] Error getting devices: TypeError: devices is not iterable
[14/02/2024, 12:20:27] [Wyze] Error getting devices: TypeError: devices is not iterable
[14/02/2024, 12:21:28] [Wyze] Error getting devices: TypeError: devices is not iterable
...

 I have now disabled the plug-in until all resolved.

**Comment by bwalls** [comment]
I was getting the same "Potentially recoverable error". Found I was logged out at Wyze with too many retries. Even after disabling the plugin and waiting, I still wasn't able to get into the Wyze website with my authentication. After 15 minutes, when I tried to log in I was told that I failed Captch (even though I was never presented with one).  I changed my password, and that got me back in. I updated the password in Homebridge and made sure the API ID and key were still active. They are. Got the error on next try, but now it seems to be working. I did set the retry timer in the configuration up to several minutes, to make lockout less likely. FIngers crossed.

**Comment by carTloyal123** [comment]
@Geczy is this resolved in the latest versions?

**Comment by carTloyal123** [comment]
Closing in favor of #216

**Comment by BBfly1** [comment]
UPDATE: 2024-0216 reset password, deleted and reset API ID/Key, upgraded to
latest ver (v0.5.44) and it now works with no errors.
