### ISSUE TITLE
Plugin reboots itself - MeshLight

### ISSUE THREAD

**Issue by orenschor** [jfarmer08/homebridge-wyze-smart-home#232]
**Describe The Bug:**
Unexpectedly, plugin reboots itself in a loop. To my understanding it is connected to the light color as sometimes it changes to green.

**To Reproduce:**
No clear steps of reproduction. It can work fine and then start to reboot. Previously when it happened, I changed the light color via the Wyze app and it stopped the errors, but after some time it reproduces.

**Expected behavior:**
Plug in will work without rebooting preferably supporting all colors but not a must.
**Logs:**

```
[3/10/2024, 11:09:11 AM] [Wyze] Restarting Process...
[3/10/2024, 11:09:12 AM] [Wyze] Launched child bridge with PID 1XX5X
[3/10/2024, 11:09:12 AM] Registering platform 'homebridge-wyze-smart-home.WyzeSmartHome'
[3/10/2024, 11:09:12 AM] [Wyze] Loaded homebridge-wyze-smart-home v0.5.46 child bridge successfully
[3/10/2024, 11:09:12 AM] Loaded 3 cached accessories from cachedAccessories.XXXXXXXXX.
[3/10/2024, 11:09:12 AM] Homebridge v1.7.0 (HAP v0.11.1) (Wyze) is running on port 49212.
/homebridge/node_modules/homebridge-wyze-smart-home/node_modules/colorsys/colorsys.js:197
  return colorsys.rgb2Hsv(rgb.r, rgb.g, rgb.b)
                              ^
TypeError: Cannot read properties of null (reading 'r')
    at Object.colorsys.hex2Hsv (/homebridge/node_modules/homebridge-wyze-smart-home/node_modules/colorsys/colorsys.js:197:31)
    at WyzeMeshLight.updateColor (/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeMeshLight.js:104:31)
    at WyzeMeshLight.updateCharacteristics (/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeMeshLight.js:69:46)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[3/10/2024, 11:09:13 AM] [Wyze] Child bridge process ended
[3/10/2024, 11:09:13 AM] [Wyze] Process Ended. Code: 1, Signal: null
```

**Plugin Config:**

```json
{
    "name": "Wyze",
    "username": "XXXX@gmail.com",
    "password": "XXXX",
    "keyId": "XXX",
    "apiKey": "XXX",
    "refreshInterval": 60000,
    "hms": false,
    "showAdvancedOptions": true,
    "apiLogEnabled": false,
    "pluginLoggingEnabled": false,
    "lowBatteryPercentage": 30,
    "excludeMacAddress": false,
    "filterByMacAddressList": [
        "XXX",
        "XXX"
    ],
    "excludedeviceType": true,
    "platform": "WyzeSmartHome",
    "_bridge": {
        "username": "XXXX",
        "port": 49212
    }
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: v0.5.46
* **Homebridge Version**: v4.55.1
* **Node.js Version**: v20.11.1
* **NPM Version**: 10.2.4
* **Operating System**: Docker on windows hyper-v

**Comment by jfarmer08** [comment]
*Update from the 2.0 work-in-progress on the [`2.0.0` branch](https://github.com/jfarmer08/homebridge-wyze-smart-home/tree/2.0.0):*

Same root cause as #251 — fixed in 2.0 (submodule commit `b514881`). The color value Wyze returned for some color/firmware combinations was null, the old `colorsys.hex2Hsv()` call dereferenced it, and the unhandled error crashed the child process into a restart loop.

In 2.0:
- Color conversion was reimplemented and now guards bad input (null / empty / non-6-hex) — returns neutral `{hue:0, saturation:0}` instead of throwing, and the bulb's true color comes through on the next refresh.
- Plugin-wide unhandled-rejection / uncaught-exception handlers keep any future stray error from crashing the process.

Please install from the 2.0 branch and confirm color changes no longer trigger the loop.
