### ISSUE TITLE
Child bridge keeps restarting

### ISSUE THREAD

**Issue by brianld75** [jfarmer08/homebridge-wyze-smart-home#270]
**Describe The Bug:**
Wyze plugin v0.5.47 keeps restarting

**To Reproduce:**
Install latest Wyze plugin.  Tried resetting Wyze API key, as well as downgrading Node.js version to 20.5.1

**Expected behavior:**
Plugin should not restart continually

**Logs:**

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeHMS.js:46
      this.getCharacteristic(Characteristic.SecuritySystemCurrentState).updateValue(noResponse);
           ^
TypeError: this.getCharacteristic is not a function
    at WyzeHMS.updateCharacteristics (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeHMS.js:46:12)
    at WyzeHMS.update (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:60:12)
    at WyzeSmartHome.loadDevice (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:157:15)
    at WyzeSmartHome.loadDevices (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:117:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WyzeSmartHome.refreshDevices (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:106:7)
    at WyzeSmartHome.runLoop (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:90:9)
[18/11/2024, 13:43:25] [Wyze] Child bridge process ended
[18/11/2024, 13:43:25] [Wyze] Process Ended. Code: 1, Signal: null
[18/11/2024, 13:43:32] [Wyze] Restarting Process...
[18/11/2024, 13:43:32] [Wyze] Launched child bridge with PID 1762
[18/11/2024, 13:43:32] Registering platform 'homebridge-wyze-smart-home.WyzeSmartHome'
[18/11/2024, 13:43:32] [Wyze] Loaded homebridge-wyze-smart-home v0.5.47 child bridge successfully
[18/11/2024, 13:43:32] Loaded 22 cached accessories from cachedAccessories.0E3E1D8DB1AA.
[18/11/2024, 13:43:32] Homebridge v1.8.5 (HAP v0.12.3) (Wyze) is running on port 51403.
[18/11/2024, 13:43:32] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeHMS.js:46
      this.getCharacteristic(Characteristic.SecuritySystemCurrentState).updateValue(noResponse);
           ^
TypeError: this.getCharacteristic is not a function
    at WyzeHMS.updateCharacteristics (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeHMS.js:46:12)
    at WyzeHMS.update (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:60:12)
    at WyzeSmartHome.loadDevice (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:157:15)
    at WyzeSmartHome.loadDevices (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:117:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WyzeSmartHome.refreshDevices (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:106:7)
    at WyzeSmartHome.runLoop (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:90:9)
[18/11/2024, 13:43:33] [Wyze] Child bridge process ended
[18/11/2024, 13:43:33] [Wyze] Process Ended. Code: 1, Signal: null
[18/11/2024, 13:43:40] [Wyze] Restarting Process...
[18/11/2024, 13:43:40] [Wyze] Launched child bridge with PID 1776
[18/11/2024, 13:43:40] [Wyze] Loaded homebridge-wyze-smart-home v0.5.47 child bridge successfully
[18/11/2024, 13:43:41] [Wyze] Child bridge process ended
[18/11/2024, 13:43:41] [Wyze] Process Ended. Code: 1, Signal: null
[18/11/2024, 13:43:48] [Wyze] Restarting Process...
[18/11/2024, 13:43:48] [Wyze] Launched child bridge with PID 1790
[18/11/2024, 13:43:48] [Wyze] Loaded homebridge-wyze-smart-home v0.5.47 child bridge successfully
[18/11/2024, 13:43:48] [Wyze] Child bridge process ended
[18/11/2024, 13:43:48] [Wyze] Process Ended. Code: 1, Signal: null

**Plugin Config:**

{
    "bridge": {
        "name": "Homebridge CA41",
        "username": "0E:32:DA:C7:CA:41",
        "port": 51499,
        "pin": "355-35-030",
        "advertiser": "avahi",
        "bind": []
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "purple",
            "tempUnits": "f",
            "lang": "en",
            "platform": "config"
        },
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": false,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "devicesUseDiscoveryPort": false,
            "platform": "TplinkSmarthome",
            "_bridge": {
                "username": "X",
                "port": 40919
            }
        },
        {
            "name": "Wyze",
            "username": "X",
            "password": "X",
            "keyId": "X",
            "apiKey": "X",
            "refreshInterval": 60000,
            "hms": true,
            "showAdvancedOptions": true,
            "apiLogEnabled": false,
            "pluginLoggingEnabled": false,
            "lowBatteryPercentage": 30,
            "excludeMacAddress": false,
            "excludedeviceType": true,
            "filterDeviceTypeList": [
                "MeshLight",
                "Camera"
            ],
            "_bridge": {
                "username": "0E:3E:1D:8D:B1:AA",
                "port": 51403
            },
            "platform": "WyzeSmartHome"
        },

**Screenshots:**

**Environment:**

* **Plugin Version**:  v0.5.47
* **Homebridge Version**: 1.8.5
* **Node.js Version**: 20.5.1
* **NPM Version**: 
* **Operating System**: Homebridge Raspbian "homebridge/homebridge-raspbian-image-1.2.0-\(64bit\)" - Raspberry Pi 5 Model B Rev 1.0

**Comment by brianld75** [comment]
Issue was due to Wyze hub being offline and needing a soft reset. Closing issue.
