### ISSUE TITLE
Might be Mfa but not sure.

### ISSUE THREAD

**Issue by vascott1** [jfarmer08/homebridge-wyze-smart-home#40]
**Describe Your Problem:**
Just upgraded to this plugin since it is verified and supports more devices. Thanks for that  :) All of my devices vanished from HomeKit so I thought it was Mia and upgraded at the same time. I am getting an m4a error but that seem to resolve and then I get this:

**Logs:**

[09/10/2022, 13:16:23] [Wyze] Error, refreshing access token and trying again
[09/10/2022, 13:16:24] [Wyze] Error, logging in and trying again
[09/10/2022, 13:16:24] [Wyze] Error getting devices: TypeError: Cannot read properties of undefined (reading 'app_id')

This could be Mfa related of course. What I did was log out of the app on my phone. Logged in again with my account and when I got my mfa code I updated it in the config ands restarted.

**Plugin Config:**

My json looks like this:

     {
            "name": "Wyze",
            "username": "xxxxxx",
            "password": "xxxxx",
            "refreshInterval": 60000,
            "mfaCode": "038772",
            "platform": "WyzeSmartHome"
        }

**Screenshots:**

**Environment:**

homebridge-wyze-smart-home v0.5.23
* **Homebridge Version**: 1.4.1
* **Node.js Version**: v16.15.0
* **NPM Version**: 8.5.5
* **Operating System**: Raspbian GNU/Linux Buster (10)

**Comment by jfarmer08** [comment]
Beta Version [0.5.24-beta.1](https://www.npmjs.com/package/homebridge-wyze-smart-home/v/0.5.24-beta.1) has been published. Please let me know if this work for you.

**Comment by geekster909** [comment]
@jfarmer08 I am also getting this after enabling 2FA on my account using text message.

I logged out of the app, logged in and got my code via text message and added it to my homebridge config and restarted.

Logs:
```
[11/24/2022, 6:07:38 PM] [Wyze] Initializing WyzeSmartHome platform...
[11/24/2022, 6:07:39 PM] [Wyze] Error, refreshing access token and trying again
[11/24/2022, 6:07:39 PM] [Wyze] Error, logging in and trying again
[11/24/2022, 6:07:40 PM] [Wyze] Error getting devices: TypeError: Cannot read properties of undefined (reading 'app_id')
```
Homebridge Version: homebridge-config-ui-x v4.50.2
Node.js Version: v18.12.1
Operating System: Raspbian
Plugin version: homebridge-wyze-smart-home v0.5.24

**Comment by phamminhtris** [comment]
I also got the same issue with the latest release

**Comment by jfarmer08** [comment]
I am looking into this. Hopefully it's a quick fix.

**Comment by jfarmer08** [comment]
Can you turn on debug logs and try it again. I would like to see the output.

**Comment by phamminhtris** [comment]
```
[04/12/2022, 11:26:34] [Wyze] Performing request: user/login
[04/12/2022, 11:26:34] [Wyze] Request config: {"method":"POST","url":"user/login","data":{"email":"<email>","password":"<password hash>"},"baseURL":"https://auth-prod.api.wyze.com","headers":{"x-api-key":"WMXHYf79Nr5gIlt3r0r7p9Tcw5bvs6BB4U8O8nGJ","User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15"}}
[04/12/2022, 11:26:34] [Wyze] API response: {"access_token":null,"refresh_token":null,"user_id":"<user_id>,"mfa_options":["PrimaryPhone"],"mfa_details":{"phone_numbers":{"primary_phone":{"country_code":"+1","number":"<phone>"},"backup_phone":null},"totp_apps":[]},"sms_session_id":"<session_id>"}
[04/12/2022, 11:26:34] [Wyze] Error getting devices: TypeError: Cannot read properties of undefined (reading 'app_id')

**Comment by jfarmer08** [comment]
So it still works when not using 2fa?

**Comment by jfarmer08** [comment]
I am testing this now, but I am not seeing the issue. It would be helpful to have the logs on debug and get the full log set for the error.

**Comment by justin-bond** [comment]
@jfarmer08 I have retested this again and it seems to work only if I don't log into the app again, once I request a new code to log into the app, homebridge stops working.

These are the steps I am taking:
1. I logged out of the app and re-logged in
2. Setup 2fa via SMS and got the code
3. Added it to my homebridge config and restarted homebridge
  a.  This works and can see/control Wyze devices
4. Resend code, so I can still log in on the app and was able to login
5. Restarted homebridge
6. Can no longer see/control wyze devices and get the following errors in the log

Logs after restarting homebridge after logging into the app with resending the code:
```
[12/10/2022, 12:57:15 AM] Loaded plugin: homebridge-wyze-smart-home@0.5.24
[12/10/2022, 12:57:15 AM] Registering platform 'homebridge-wyze-smart-home.WyzeSmartHome'
[12/10/2022, 12:57:15 AM] [Wyze] Initializing WyzeSmartHome platform...
[12/10/2022, 12:57:15 AM] [Wyze] [WyzePlug] Fetching status of "Front Yard 2"
[12/10/2022, 12:57:15 AM] [Wyze] [WyzePlug] Retrieving previous service for "Front Yard 2"
[12/10/2022, 12:57:15 AM] [Wyze] [WyzePlug] Fetching status of "Front Yard 1"
[12/10/2022, 12:57:15 AM] [Wyze] [WyzePlug] Retrieving previous service for "Front Yard 1"
[12/10/2022, 12:57:15 AM] [Wyze] [WyzePlug] Fetching status of "Outdoor Plug 2"
[12/10/2022, 12:57:15 AM] [Wyze] [WyzePlug] Retrieving previous service for "Outdoor Plug 2"
[12/10/2022, 12:57:15 AM] [Wyze] [WyzePlug] Fetching status of "Outdoor Plug 1"
[12/10/2022, 12:57:15 AM] [Wyze] [WyzePlug] Retrieving previous service for "Outdoor Plug 1"
[12/10/2022, 12:57:15 AM] [Wyze] [WyzePlug] Fetching status of "Plug 1"
[12/10/2022, 12:57:15 AM] [Wyze] [WyzePlug] Retrieving previous service for "Plug 1"
[12/10/2022, 12:57:15 AM] [Wyze] [WyzePlug] Fetching status of "Plug 2"
[12/10/2022, 12:57:15 AM] [Wyze] [WyzePlug] Retrieving previous service for "Plug 2"
[12/10/2022, 12:57:15 AM] [Wyze] Refreshing devices...
[12/10/2022, 12:57:16 AM] [Wyze] Performing request: app/v2/home_page/get_object_list
[12/10/2022, 12:57:16 AM] [Wyze] Request config: {"method":"POST","url":"app/v2/home_page/get_object_list","data":{"access_token":"lvtx.MtSuvK0EzoxnNZdCzLVEC4uEeXWChQWqRfxL69ILBp1jiTdkQQZhssNkZsa45QgA+aZmlQ36LL1LCPBxNa90rNC60i57LM4XB2rFFIqtWsKVxy9SEU8TwPZa8XkBiasNiUz50YAe243VEWxuOxtEB6pfHtUFtiYFtc/bGxfKKk7yyOCSJDiICtDyU8sG99fQ32sNug==","app_name":"com.hualai.WyzeCam","app_ver":"com.hualai.WyzeCam___2.18.44","app_version":"2.18.44","phone_id":"<phone_id>","phone_system_type":"1","sc":"9f275790cab94a72bd206c8876429f3c","sv":"9d74946e652647e9b6c9d59326aef104","ts":1670633836206},"baseURL":"https://api.wyzecam.com"}
[12/10/2022, 12:57:16 AM] [Wyze] API response: {"ts":1670633836515,"code":"2001","msg":"AccessTokenError","data":{}}
[12/10/2022, 12:57:16 AM] [Wyze] Error: AccessTokenError
    at WyzeAPI._performRequest (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeAPI.js:119:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WyzeAPI.request (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeAPI.js:65:14)
    at WyzeAPI.getObjectList (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeAPI.js:218:20)
    at WyzeSmartHome.refreshDevices (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:68:26)
    at WyzeSmartHome.runLoop (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:57:9)
[12/10/2022, 12:57:16 AM] [Wyze] Error, refreshing access token and trying again
[12/10/2022, 12:57:16 AM] [Wyze] Performing request: app/user/refresh_token
[12/10/2022, 12:57:16 AM] [Wyze] Request config: {"method":"POST","url":"app/user/refresh_token","data":{"access_token":"<acces_token_hash>","app_name":"com.hualai.WyzeCam","app_ver":"com.hualai.WyzeCam___2.18.44","app_version":"2.18.44","phone_id":"bc151f39-787b-4871-be27-5a20fd0a1937","phone_system_type":"1","sc":"9f275790cab94a72bd206c8876429f3c","sv":"9d74946e652647e9b6c9d59326aef104","ts":1670633836629,"refresh_token":"lvtx.topDsOfM9GUarix6c5/B7QvwZOSq0YBRTUunITCPOPVcYKIciOf6D98iruknkG2cXQNwGjdakIjUdjSx35a87lo+g+1RvJPF5xcQvms4OHE5lLUIrEDR/wF2E+CKztRHlvPcPb0vdoDYkESWp+fH7Mwa/yY7DDabSc8dQWct+XGQnh8G0/xYQWedulU/lB8HEJWHZQ=="},"baseURL":"https://api.wyzecam.com"}
[12/10/2022, 12:57:16 AM] [Wyze] API response: {"ts":1670633836775,"code":"2002","msg":"RefreshTokenError","data":{}}
[12/10/2022, 12:57:16 AM] [Wyze] Error, logging in and trying again
[12/10/2022, 12:57:16 AM] [Wyze] Performing request: user/login
[12/10/2022, 12:57:16 AM] [Wyze] Request config: {"method":"POST","url":"user/login","data":{"email":"<email>","password":"<password_hash>"},"baseURL":"https://auth-prod.api.wyze.com","headers":{"x-api-key":"WMXHYf79Nr5gIlt3r0r7p9Tcw5bvs6BB4U8O8nGJ","User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15"}}
[12/10/2022, 12:57:17 AM] [Wyze] API response: {"access_token":null,"refresh_token":null,"user_id":"<user_id>","mfa_options":["PrimaryPhone"],"mfa_details":{"phone_numbers":{"primary_phone":{"country_code":"+1","number":"<phone_number>"},"backup_phone":null},"totp_apps":[]},"sms_session_id":"<sms_session_id>"}
[12/10/2022, 12:57:17 AM] [Wyze] Error getting devices: TypeError: Cannot read properties of undefined (reading 'app_id')
```
Note: <*> is my information that I blocked

**Comment by mattapperson** [comment]
So the issue seems to be using sms based 2fa or an app... app works, sms does not. When using phone based SMS an additional API call is sent to trigger the sending of the code... the code from logging in on your phone is not the same... for example.... if I log out of my app and my wife's app that uses the same login, just 2 devices... the code generated from logging back in on my device does not work when entered on her device

**Comment by jfarmer08** [comment]
@mattapperson you are correct. So in the current form this plugin does not support sms correctly. I think the best approach is to create a custom http page for this type of service. Not sure when I will have time to look at this.

**Comment by mattapperson** [comment]
Agreed. In the interim perhaps adding an error message that makes this easy to understand?

**Comment by jfarmer08** [comment]
I found time today to work a little on this. I think I have solution. I will put something out when I can.

**Comment by jfarmer08** [comment]
Would someone create a new request for SMS MFA support.

**Comment by jfarmer08** [comment]
This seems to be around SMS MFA so I will lock this thread until we have support for it.
