### ISSUE TITLE
Child bridge icon was flashing red/yellow

### ISSUE THREAD

**Issue by vascott1** [jfarmer08/homebridge-wyze-smart-home#41]
I installed the plugin a few days ago and it was working fine after I turned off 2 Factor. Yesterday all was well but I woke up to see that my child bridge icon was flashing red/yellow. Looking at the logs I see this:

[10/23/2022, 12:06:35 PM] Loaded 17 cached accessories from cachedAccessories.0E56DD166B87.
Error: Cannot find the bridged Accessory to remove.
    at Bridge.Accessory.removeBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:640:13)
    at Bridge.Accessory.removeBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:654:12)
    at BridgeService.handleUnregisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:404:17)
    at HomebridgeAPI.emit (node:events:527:28)
    at HomebridgeAPI.unregisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:355:10)
    at WyzeSmartHome.configureAccessory (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:171:16)
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:328:25
    at Array.filter (<anonymous>)
    at BridgeService.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:288:69)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:186:24)

I have not added or removed any devices. Certainly not in my sleep :) Looking in the Wyze app I see all of my devices are online and working fine. I tried restarting the plugin and I restarted homebridge to no avail. What I finally had to do is disable this plugin and switch back to homebridge-wyze-connected-home-op v0.5.9

I would certainly prefer to use this plugin as it is verified and has support for the cameras which is pretty cool. 

Any ideas how to fix this?

**Comment by jfarmer08** [comment]
Do you have Outdoor plugs?

**Comment by jfarmer08** [comment]
Beta Version [0.5.24-beta.1](https://www.npmjs.com/package/homebridge-wyze-smart-home/v/0.5.24-beta.1) has been published. Please let me know if this work for you.
