### ISSUE TITLE
Loop after server restart

### ISSUE THREAD

**Issue by jscherry** [jfarmer08/homebridge-wyze-smart-home#43]
**Describe The Bug:**
Every time I restart the homebridge server the wyze plugin gets stuck in a loop and won't load. The only way I've been able to get it working again is to uninstall the plugin and then reinstall it? It's done the same thing on two different computers; Windows 10 and 11? If there's something I can change in the config etc please let me know. I love the plugin just not having to reinstall it every time the server reboots. Thanks.

**To Reproduce:**
Restart the homebridge server.
**Expected behavior:**
To load the plugin as normal

**Logs:**
[11/12/2022, 7:22:17 PM] [Wyze] Child bridge process ended
[11/12/2022, 7:22:17 PM] [Wyze] Process Ended. Code: 1, Signal: null
[11/12/2022, 7:22:21 PM] [eWeLink] [Printer Plug] current power [2.76W] current voltage [127.55V] current current [0.06A].
[11/12/2022, 7:22:21 PM] [eWeLink] [Printer Plug] current power [2.76W] current voltage [127.55V] current current [0.06A].
[11/12/2022, 7:22:24 PM] [Wyze] Restarting Process...
[11/12/2022, 7:22:26 PM] [eWeLink] [Plug Dehumidifier ] current power [483.14W] current voltage [120.64V] current current [4.13A].
[11/12/2022, 7:22:26 PM] [eWeLink] [Plug Dehumidifier ] current power [483.14W] current voltage [120.64V] current current [4.13A].
[11/12/2022, 7:22:27 PM] [eWeLink] [Foyer V3 Plug] current power [2.5W] current voltage [124.65V] current current [0.05A].
[11/12/2022, 7:22:27 PM] [eWeLink] [Foyer V3 Plug] current power [2.50W] current voltage [124.65V] current current [0.05A].
[11/12/2022, 7:22:30 PM] [Wyze] Launched child bridge with PID 34224
[11/12/2022, 7:22:31 PM] Registering platform 'homebridge-wyze-smart-home.WyzeSmartHome'
[11/12/2022, 7:22:31 PM] [Wyze] Loaded homebridge-wyze-smart-home v0.5.23 child bridge successfully
[11/12/2022, 7:22:31 PM] Loaded 57 cached accessories from cachedAccessories.0E349189F49A.
Error: Cannot find the bridged Accessory to remove.
    at Bridge.Accessory.removeBridgedAccessory (C:\Users\Jeff\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Accessory.ts:640:13)
    at Bridge.Accessory.removeBridgedAccessories (C:\Users\Jeff\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Accessory.ts:654:12)
    at BridgeService.handleUnregisterPlatformAccessories (C:\Users\Jeff\AppData\Roaming\npm\node_modules\homebridge\src\bridgeService.ts:404:17)
    at HomebridgeAPI.emit (node:events:513:28)
    at HomebridgeAPI.unregisterPlatformAccessories (C:\Users\Jeff\AppData\Roaming\npm\node_modules\homebridge\src\api.ts:355:10)
    at WyzeSmartHome.configureAccessory (C:\Users\Jeff\AppData\Roaming\npm\node_modules\homebridge-wyze-smart-home\src\WyzeSmartHome.js:171:16)
    at C:\Users\Jeff\AppData\Roaming\npm\node_modules\homebridge\src\bridgeService.ts:328:25
    at Array.filter (<anonymous>)
    at BridgeService.restoreCachedPlatformAccessories (C:\Users\Jeff\AppData\Roaming\npm\node_modules\homebridge\src\bridgeService.ts:288:69)
    at ChildBridgeFork.startBridge (C:\Users\Jeff\AppData\Roaming\npm\node_modules\homebridge\src\childBridgeFork.ts:186:24)
[11/12/2022, 7:22:32 PM] [Wyze] Child bridge process ended
[11/12/2022, 7:22:32 PM] [Wyze] Process Ended. Code: 1, Signal: null
[11/12/2022, 7:22:39 PM] [Wyze] Restarting Process...
```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```
{
    "name": "Wyze",
    "username": "jexxxxxxxx@xx.com",
    "password": "xxxxxxxxxx",
    "refreshInterval": 60000,
    "platform": "WyzeSmartHome",
    "_bridge": {
        "username": "xxxxxxxxxxxxxxx",
        "port": 56893
    }
}

**Screenshots:**

**Environment:**
Windows 10 nodes.

* **Plugin Version**: [v0.5.23] Running as a child bridge.
* **Homebridge Version**: [v1.5.1]
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**: Windows 10 or 11

**Comment by idooo** [comment]
+1 have the same issue

Environment: Linux raspberrypi 5.4.51-v7l+ armv7l GNU/Linux
Plugin version: homebridge-wyze-smart-home v0.5.23

**Comment by MikeyJ23** [comment]
+1 here too have the same issue

Environment: Windows 10
Plugin version: homebridge-wyze-smart-home v0.5.23

**Comment by jscherry** [comment]
The Windows 10 computer running homebridge just rebooted and exact smae thing, logs below. Surely someone here knows whats causing this or possibly something we can do to fix it?

[11/17/2022, 7:31:12 PM] [Wyze] Loaded homebridge-wyze-smart-home v0.5.23 child bridge successfully
[11/17/2022, 7:31:12 PM] Loaded 57 cached accessories from cachedAccessories.0EC7C6D3DCAD.
Error: Cannot find the bridged Accessory to remove.
    at Bridge.Accessory.removeBridgedAccessory (C:\Users\Jeff\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Accessory.ts:640:13)
    at Bridge.Accessory.removeBridgedAccessories (C:\Users\Jeff\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Accessory.ts:654:12)
    at BridgeService.handleUnregisterPlatformAccessories (C:\Users\Jeff\AppData\Roaming\npm\node_modules\homebridge\src\bridgeService.ts:404:17)
    at HomebridgeAPI.emit (node:events:513:28)
    at HomebridgeAPI.unregisterPlatformAccessories (C:\Users\Jeff\AppData\Roaming\npm\node_modules\homebridge\src\api.ts:355:10)
    at WyzeSmartHome.configureAccessory (C:\Users\Jeff\AppData\Roaming\npm\node_modules\homebridge-wyze-smart-home\src\WyzeSmartHome.js:171:16)
    at C:\Users\Jeff\AppData\Roaming\npm\node_modules\homebridge\src\bridgeService.ts:328:25
    at Array.filter (<anonymous>)
    at BridgeService.restoreCachedPlatformAccessories (C:\Users\Jeff\AppData\Roaming\npm\node_modules\homebridge\src\bridgeService.ts:288:69)
    at ChildBridgeFork.startBridge (C:\Users\Jeff\AppData\Roaming\npm\node_modules\homebridge\src\childBridgeFork.ts:186:24)

**Comment by jfarmer08** [comment]
Beta Version [0.5.24-beta.1](https://www.npmjs.com/package/homebridge-wyze-smart-home/v/0.5.24-beta.1) has been published. Please let me know if this work for you.

**Comment by MikeyJ23** [comment]
That seems to have solved it for me! Very much appreciate your work
