### ISSUE TITLE
Child bridge will not start. 

### ISSUE THREAD

**Issue by vascott1** [jfarmer08/homebridge-wyze-smart-home#48]
**Describe Your Problem:**
Unable to start my child bridge. I am seeing the same issue with homebridge-wyze-connected-home-op v0.5.9 I am not using 2 factor with my Wyze account

**Logs:**
[27/11/2022, 18:04:40] [wyze-smart-home] Restarting Process...
[27/11/2022, 18:04:42] [wyze-smart-home] Launched child bridge with PID 29108
[11/27/2022, 6:04:42 PM] Registering platform 'homebridge-wyze-smart-home.WyzeSmartHome'
[27/11/2022, 18:04:42] [wyze-smart-home] Loaded homebridge-wyze-smart-home v0.5.24 child bridge successfully
[11/27/2022, 6:04:42 PM] Loaded 17 cached accessories from cachedAccessories.0E56DD166B87.
Error: Cannot find the bridged Accessory to remove.
    at Bridge.Accessory.removeBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:640:13)
    at Bridge.Accessory.removeBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:654:12)
    at BridgeService.handleUnregisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:404:17)
    at HomebridgeAPI.emit (node:events:527:28)
    at HomebridgeAPI.unregisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:355:10)
    at WyzeSmartHome.configureAccessory (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:186:16)
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:328:25
    at Array.filter (<anonymous>)
    at BridgeService.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:288:69)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:186:24)
[27/11/2022, 18:04:42] [wyze-smart-home] Child bridge process ended
[27/11/2022, 18:04:42] [wyze-smart-home] Process Ended. Code: 1, Signal: null
```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
 {
        "name": "Wyze",
        "username": "xxxxxx",
        "password": "xxxxx",
        "refreshInterval": 60000,
        "mfaCode": "038772",
        "platform": "WyzeSmartHome"
    }
```

**Screenshots:**

**Environment:**

homebridge-wyze-smart-home v0.5.23
	•	Homebridge Version: 1.5.0
	•	Node.js Version: v16.15.0
	•	NPM Version: 8.5.5
	•	Operating System: Raspbian GNU/Linux Buster (10)

**Comment by Awire9966** [comment]
Child bridges in homebridge are buggy to begin with. I dont use child bridges to begin with.

**Comment by vascott1** [comment]
I will try I doing it but it has been working great as a child bridge. Odd that it happens on both. I use ring that way and dynamic home. Let’s see what happens :)
  
  
  
  
  
  
  

  
  
>

**Comment by jfarmer08** [comment]
Have you tired using https://www.npmjs.com/package/homebridge-wyze-smart-home/v/0.5.24

**Comment by vascott1** [comment]
I am using that version of the plug-in and it is working well now as a non child bridge. I am not sure where to put the block you suggest but would certainly give it a try. Would that allow me to run it as a child bridge once again?

Thanks!

**Comment by jfarmer08** [comment]
The code is already in place on version 0.5.24. Thats why I ask if you had tried using a child bridge on this version. There is nothing that you can do unless you want to try it again with version 0.5.24 and collect logs. I would be nice to have logs from before and after you enable the child bridge.

**Comment by jfarmer08** [comment]
I have been testing the child bridge for a few weeks now and I have not seen any issues. I am also using beta 3

**Comment by jfarmer08** [comment]
Have you been able to test this on the current beta release?
