### ISSUE TITLE
TypeError: Cannot convert undefined or nul 1 to object at Function.keys (<anonymous>) at WyzeLock.lockGetProperty

### ISSUE THREAD

**Issue by kris1254** [jfarmer08/homebridge-wyze-smart-home#91]
Error with Wyze lock and version V0.5.26 causing homebridge to repeatedly restart.

I have two wyze locks, one Bluetooth keypad version, the other is wifi model. The plug-in seems to have issues with the Bluetooth, instead of ignoring its lack communication it is complaining endlessly.

[29/03/2023, 21:31:40] Homebridge v1. 6.0 (
HAP v0.11.0) (Wyze) is running on port 372
71・
/usr/local/lib/node modules /homebridge-wyz e-smart-home/src/accessories/WyzeAccessory .js: 384
const prop_key = Object.keys (lockPrope
rties)
TypeError: Cannot convert undefined or nul
1 to object
at Function.keys (<anonymous>)
at WyzeLock.lockGetProperty (/usr/loca
1/lib/node modules/homebridge-wyze-smart-h ome/src/accessories/wyzeAccessory.js:384:2
9)
at processTicksAndRejections (node: int ernal/process/task queues:96:5)
[29/03/2023, 21:31:40] [Wyze] Child bridge process ended
[29/03/2023, 21:31:40] [Wyze] Process Ende
d. Code: 1, Signal: null

**Plugin Config:**

{
    "bridge": {
        "name": "Homebridge 7469",
        "username": "0E:FC:FA:DB:C2:A2",
        "port": 51478,
        "pin": "530-05-629"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Wyze",
            "username": "",
            "password": “",
            "refreshInterval": 60000,
            "mfaCode": "",
            "_bridge": {
                "username": "0E:5D:5C:82:12:B4",
                "port": 37271
            },
            "platform": "WyzeSmartHome"
        }
    ]
}

**Comment by jfarmer08** [comment]
Can you put that lock into the ignore list?

**Comment by kris1254** [comment]
I’m not able to add it to the ignore list via MAC, it is a bluetooth device and not sure it can distinguish that.  As well if I exclude by device type, of course it removes my wifi enabled Wyze lock.

**Comment by chris001** [comment]
Same error on the **WyzeLock (wifi) Keypad**, I don't own the optional keypad for wyze lock(wifi).  I have only the wyze lock (wifi).

The plugin keeps restarting infinitely, about every 5 seconds, status is red for about 5 seconds, then yellow, then green, then red again immediately.

```
[6/6/2023, 7:40:00 AM] Homebridge v1.6.1 (HAP v0.11.1) (Wyze) is running on port 46785.

/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:422
    const prop_keypad = Object.keys(lockKeypadProperties)
                               ^
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at WyzeLock.lockGetProperty (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:422:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[6/6/2023, 7:40:01 AM] [Wyze] Child bridge process ended
[6/6/2023, 7:40:01 AM] [Wyze] Process Ended. Code: 1, Signal: null
[6/6/2023, 7:40:08 AM] [Wyze] Restarting Process...
[6/6/2023, 7:40:10 AM] [Wyze] Launched child bridge with PID 2874
[6/6/2023, 7:40:11 AM] Registering platform 'homebridge-wyze-smart-home.WyzeSmartHome'
[6/6/2023, 7:40:11 AM] [Wyze] Loaded homebridge-wyze-smart-home v0.5.26 child bridge successfully
[6/6/2023, 7:40:11 AM] Loaded 15 cached accessories from cachedAccessories.0E69AE9E1C7C.
[6/6/2023, 7:40:11 AM] Homebridge v1.6.1 (HAP v0.11.1) (Wyze) is running on port 46785.

/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:422
    const prop_keypad = Object.keys(lockKeypadProperties)
                               ^
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at WyzeLock.lockGetProperty (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:422:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[6/6/2023, 7:40:12 AM] [Wyze] Child bridge process ended
[6/6/2023, 7:40:12 AM] [Wyze] Process Ended. Code: 1, Signal: null
[6/6/2023, 7:40:19 AM] [Wyze] Restarting Process...
[6/6/2023, 7:40:21 AM] [Wyze] Launched child bridge with PID 2899
[6/6/2023, 7:40:21 AM] Registering platform 'homebridge-wyze-smart-home.WyzeSmartHome'
[6/6/2023, 7:40:21 AM] [Wyze] Loaded homebridge-wyze-smart-home v0.5.26 child bridge successfully
[6/6/2023, 7:40:21 AM] Loaded 15 cached accessories from cachedAccessories.0E69AE9E1C7C.
[6/6/2023, 7:40:22 AM] Homebridge v1.6.1 (HAP v0.11.1) (Wyze) is running on port 46785.

/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:422
    const prop_keypad = Object.keys(lockKeypadProperties)
                               ^
```
Any idea what's causing this infinitely looping crash and restart bug?
