### ISSUE TITLE
Error causing HB to restart

### ISSUE THREAD

**Issue by dallasjanssen** [jfarmer08/homebridge-wyze-smart-home#98]
Seeing the below error and causing Homebridge service to restart. HMS was working without error prior to updating to 0.5.26

TypeError: this.getCharacteristic is not a function
    at WyzeHMS.updateCharacteristics (/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeHMS.js:24:12)
    at WyzeHMS.update (/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:351:18)
    at WyzeSmartHome.loadDevice (/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:126:17)
    at WyzeSmartHome.loadDevices (/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:86:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WyzeSmartHome.refreshDevices (/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:75:7)
    at WyzeSmartHome.runLoop (/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:59:9)

**Comment by dallasjanssen** [comment]
Turns out this was caused by my Hub being offline.
